apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bol.fullname" . }}-config
type: Opaque
stringData:
  config.yaml: |
      artifactRepository: {{ toYaml (required "config.artifactRepository is required" .Values.config.artifactRepository) | nindent 8 }}

      clusters: {{ toYaml (required "config.clusters is required" .Values.config.clusters) | nindent 8 }}

      {{- with .Values.config.fileNameSuffix }}
      fileNameSuffix: {{ . }}
      {{- end }}

      {{- with .Values.config.maximumReportingWindowInDays }}
      maximumReportingWindowInDays: {{ . }}
      {{- end }}
